version: '3.7'

services:
    php-httpd:
        # image: php:7.3-apache
        build:
            context: ./php-httpd
        ports:
            - 80:80
        volumes:
            - "./app:/var/www/html"

    mariadb:
        image: mariadb:10.5.2
        volumes:
            - mariadb-volume:/var/lib/mysql
        environment:
            TZ: "America/Sao_Paulo"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_DATABASE: 'appdb'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - 'mariadb:db'
        ports:
            - 8081:80
    
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080

volumes:
    mariadb-volume: